{% set name = "handlebars.js" %}
{% set version = "4.7.0" %}
{% set sha256 = "830c6d37a5b4cc9e8b0eb282769e0cddea8b4a35e744868b463b12fa2e7b0851" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wycats/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g handlebars
  requires:
    - nodejs
   

about:
  home: https://github.com/wycats/handlebars.js/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Handlebars provides the power necessary to let you build semantic templates effectively with no frustration.'
  description: |
    Handlebars provides the power necessary to let you build semantic templates 
    effectively with no frustration. Handlebars is largely compatible with Mustache 
    templates. In most cases it is possible to swap out Mustache with Handlebars 
    and continue using your current templates. 
  doc_url: https://www.sitepoint.com/a-beginners-guide-to-handlebars/
  dev_url: https://github.com/wycats/handlebars.js/

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
