travis:
  secure:
    BINSTAR_TOKEN: XUfA+zioGDcb2nNooZ45mRweQso5bwkFxTyrfaP52fPLMYRIi9WLPaHPGe6x5ieK//z1E49MnYDObZw5Ztb48eStws7+YSt1/nje0PhHBkU+bsJ6O2sOtfTyh90/kMNQaovz1wkYvnTs7U4eop7N27PtNM0O4+Z2XOgqMsXWW3BBRGyDaC9tpiJKuDetDyNf/hkI7uhLfEj9oXLqtg79ZR4uvfv8G2GH0CX7IFrZPiheToKW0EVIdI3BnJOk2fwWu705+mpSKfye8ODn3/vUGypk0TU88SmeXTcz9lZeY2GNEs43Z0zzwjKiAuY5yd7S5JEorWj5djnMz5ito8HMqGEt5pANL0eNRdhm0mncIwq4z4Lw/aIiSBgeiJKaDNNNMBI5Nr+bLZFPSuYJ0ZjgYG8f21X3tOCOeT6vwgLHL+GhcbbIsz1A/7Hr9jJOHfMRlD8imTASvZgDIalfoxcZsRVk2bh3Dgglv/X3tXcxz8MGPuTNZoJHDGT3e8ISwjIb+CXH/PGwcxzY74oDeDQFeVLhPl1Kj0DwzMsB2qufndANkJeVHVjUjqpzvv6qmSyePol7Mu3Q3QpJ10P7IKoqencfi5mRTNqFVCLk6ExBQwB4XzqMJvkvfZgPsLEITxj347RwX2ingFsWQC3x42ql/qXZYSfTNPkWfVfpEGpE3Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
