travis:
  secure:
    BINSTAR_TOKEN: aCHaQMqOVqe8KtixIIa4vrnumCJYOAMB+y3hWX6NxCQpeHJfgMToEZv2pMnX0FADaAP7ziu9hiyPcUu3fNk0Lf5SjyGsQpzBae/YwJkQbitgFmDCtUUVsCU/FJ2mmIMT9YAkrKPRKs3fRo+wMMIjDabJgWKNeATrhWc5lXZzpRNmIcWa7kUonIpHuTLDGZ6nqZLyLl4KsB50bgw+kfghhuk/Z6Eg1j/pHviB/YFJiLOWPwLzqlP73gnnO2rMonb+nHf9MCOgDrl//1mLhv5jkOvqs6YqF/9WInGYO1APbWruBlXvTpiINo05i1AwLat2FioHRtFOQgrJ8H0ftJbeAKwkmaUdwKDBDIyn4O4jGV6Ih8rjbe6tnD8H+Fy9WJZYF7dzz+3nV9AB40aE28m8cs7tWla4kmbXdqw20Lk662XqjtAnDe59kbdBQ2AkbPs3fnB6lUgTdVRY+f6oyi0VmJuqnsI7YTOPgwYhkduPuds1Y4akzlKbWivzwDTHT7678ITj0fgTt9n4AbBW6fBtL7/QP0oOSzAoDzgXN6adlUdzWNVGN+Zl/1TE8wBtrQtST8AvCWFAqv4fxvP3YPxYoXp2kAIObozMr/nH8Z4MKwsTC2iZUHuhyGZ90nmaRLkzoDcMiUYhLhepMV5Id371dah+NG+l/eii4R9w3hoEuPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
