travis:
  secure:
    BINSTAR_TOKEN: jQ+lSrd389cqDoayNp+yVAypr3F7t10S6CJb1C4W+BuAUkqOCD8s0XVfp09s0HZY7rjf5FIZomEPj3Zu+lZrcaB0FEnPmoPIfSBvfsauPIegWTQrv+t2RCXKxRnGy19EWan2vy+JkKNWD+NGPWzNV4relrOWAEPe4JD1feiG5rHfBmgoKltZ0htn4yYfJ7MXJSKkbA+b40r2cho8/WYluWHn0j2b9oiSFvaXsrvwCfKydf13OXxOihkn/AKoc1imHkfnpcxvWdT+jC1P+DJzIatehFFbp+GgKKScV1+d7l5RgR6LukgQ1HirpTLNy2k1r56ara4gLROBJWohkzB9NUPjiQe3zu5QgRCc6ojgkSpBu+b5HFOr+IaMSBD3UO4jzPKcfZtlaI+gYgMrDLBVqEjc+1W925K3wnI7QysfG8CGRyoIFVTPKo2FZHbHH30zYtka3scza/98FUWgd2Qn3y36c0CujHP/TYacweQBFpQN27ioNjLli2Q47sjmH7wH7/dZUS52pbElwtCKaZMQRSBRc9Fg4ALTdUy4oj00W8qWILTfG0ev9UxonBQRBTnZOSbHgy2fhhbUo3XLjxGacAE50zDrc8eQ+dQOKMxIeMOS0l7SVw8ajFMDOn1nIFr+rtVz7dIbQ11udDKITXvUvOnqFUwoiV6CaW7etxAtfdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
